// <auto-generated />
namespace Yuruisoft.RS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170615_DisabledDynamicModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170615_DisabledDynamicModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201706150130361_20170615_DisabledDynamicModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
