//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuruisoft.RS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MathtoolDBEntities : DbContext
    {
        public MathtoolDBEntities()
            : base("name=MathtoolDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<math_key_and_level> math_key_and_level { get; set; }
        public DbSet<math_level_data> math_level_data { get; set; }
        public DbSet<math_search_key> math_search_key { get; set; }
        public DbSet<math_user_info> math_user_info { get; set; }
        public DbSet<math_AbilityContent> math_AbilityContent { get; set; }
        public DbSet<math_FeedBackInfo> math_FeedBackInfo { get; set; }
        public DbSet<math_SourceBuy> math_SourceBuy { get; set; }
        public DbSet<math_SourceBuyOrderstatus> math_SourceBuyOrderstatus { get; set; }
    }
}
