//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuruisoft.RS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class math_FeedBackInfo
    {
        public int ID { get; set; }
        public string nickName { get; set; }
        public string openId { get; set; }
        public string FeedBackWords { get; set; }
        public Nullable<long> phoneNum { get; set; }
        public Nullable<long> qq { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public string Remark { get; set; }
    }
}
