//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuruisoft.RS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class math_user_info
    {
        public string openId { get; set; }
        public string session_key { get; set; }
        public string nickName { get; set; }
        public string gender { get; set; }
        public string language { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string country { get; set; }
        public string avatarUrl { get; set; }
        public string watermark_timestamp { get; set; }
        public string appid { get; set; }
        public string unionId { get; set; }
        public string math_score { get; set; }
        public string yuruisoft_session_key { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Remark { get; set; }
    }
}
