//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuruisoft.RS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class math_SourceBuy
    {
        public int id { get; set; }
        public string SBContent { get; set; }
        public string SBContentImage { get; set; }
        public string SBTitle { get; set; }
        public string SBTitleImage { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public Nullable<System.DateTime> ModiyTime { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Remark { get; set; }
        public Nullable<int> TotalFee { get; set; }
        public string WxBody { get; set; }
        public string SurportTitle { get; set; }
        public string SurportDetail { get; set; }
        public string SourceUrl { get; set; }
    }
}
