//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuruisoft.RS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class math_level_data
    {
        public Nullable<int> order_all { get; set; }
        public string url { get; set; }
        public int order_in { get; set; }
        public string first_level { get; set; }
        public string second_level { get; set; }
        public string third_level { get; set; }
        public string fourth_level { get; set; }
        public string fifth_level { get; set; }
        public string full_key { get; set; }
    }
}
