//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuruisoft.RS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WxDic_SearchKey_EnToCn_C_stuvwxyz
    {
        public int id { get; set; }
        public string SKey { get; set; }
    }
}
