//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuruisoft.RS.Model.wxShoppingMall
{
    using System;
    using System.Collections.Generic;
    
    public partial class haowanFamilyAccountInfo
    {
        public int id { get; set; }
        public string account { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public long phoneNumber { get; set; }
        public System.DateTime subtime { get; set; }
        public System.DateTime modifiedOn { get; set; }
        public string remark { get; set; }
        public Nullable<int> sort { get; set; }
    }
}
