//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuruisoft.RS.Model.wxShoppingMall
{
    using System;
    using System.Collections.Generic;
    
    public partial class wxShoppingMall_produceInfo
    {
        public int id { get; set; }
        public string listTitle { get; set; }
        public string listImageUrl { get; set; }
        public Nullable<int> evaluationCount { get; set; }
        public Nullable<double> evaluationPercent { get; set; }
        public Nullable<double> price { get; set; }
        public string unit { get; set; }
        public Nullable<System.DateTime> subTime { get; set; }
        public Nullable<System.DateTime> modiyTime { get; set; }
        public Nullable<int> sort { get; set; }
        public string remark { get; set; }
    }
}
