//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuruisoft.RS.Model.wxShoppingMall
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wxShoppingMallEntities : DbContext
    {
        public wxShoppingMallEntities()
            : base("name=wxShoppingMallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<haowanFamilyAccountInfo> haowanFamilyAccountInfo { get; set; }
        public virtual DbSet<wxShoppingMall_merchantInfo> wxShoppingMall_merchantInfo { get; set; }
        public virtual DbSet<wxShoppingMall_orderInfo> wxShoppingMall_orderInfo { get; set; }
        public virtual DbSet<wxShoppingMall_produceInfo> wxShoppingMall_produceInfo { get; set; }
        public virtual DbSet<wxShoppingMall_userInfo> wxShoppingMall_userInfo { get; set; }
    }
}
